import React from "react";
import { useLanguage } from "../contexts/LanguageContext";
import { useNavigate } from "react-router-dom";
import Header from "./header";

const PublicOfferScreen = () => {
  const { language } = useLanguage();
  const navigate = useNavigate();

  const translations = {
    ru: {
      title: "Публичная оферта",
      back: "Назад",
      fullText: `
Публичная оферта на использование онлайн-панели опросов «ProSurvey»

1. Общие положения
1.1. Настоящий документ является публичной офертой ООО «PROSURVEY» (далее – Компания) и адресован неопределенному кругу лиц – посетителям и пользователям онлайн-панели опросов «ProSurvey» (далее – Панель или Сервис). Данный документ содержит все существенные условия договора и считается публичной офертой в соответствии со статьями 367 и 369 Гражданского кодекса Республики Узбекистан.
1.2. Акцептом (принятием) настоящей оферты считается совершение Пользователем действий, свидетельствующих о согласии заключить договор с Компанией на указанных условиях. В частности, полной и безоговорочной акцептом признается регистрация Пользователя на сайте Панели и начало использования Сервиса. С момента акцепта оферты договор между Компанией и Пользователем считается заключенным.
1.3. Если Пользователь не согласен с каким-либо условием настоящей оферты, он должен воздержаться от регистрации и использования Сервиса. Продолжение использования Панели означает полное согласие Пользователя с условиями данной публичной оферты. Лицо, акцептовавшее оферту, тем самым подтверждает, что обладает необходимой правоспособностью и дееспособностью для заключения договора в соответствии с законодательством Республики Узбекистан.
1.4. Компания оставляет за собой право вносить изменения в условия настоящей публичной оферты. Изменения вступают в силу после размещения обновленного текста оферты на сайте Панели, либо через иной указанный срок с момента публикации изменений. Компания обязуется уведомлять Пользователей о таких изменениях путем публикации соответствующего объявления на сайте не менее чем за 10 (десять) рабочих дней до даты вступления изменений в силу[3]. Продолжение использования Сервиса после внесения изменений означает согласие Пользователя с новой редакцией оферты. При этом изменения условий оферты не имеют обратной силы и не влияют на права и обязанности, возникшие у Сторон до вступления изменений в силу.
2. Предмет договора (услуги компании)
2.1. По настоящему договору Компания предоставляет Пользователю доступ к онлайн-платформе «ProSurvey» для участия в опросах (социологических, маркетинговых и иных исследованиях), проводимых по заказу третьих лиц – партнеров или клиентов Компании. Пользователь, в свою очередь, получает возможность проходить опросы через Панель и получать за это вознаграждение в виде денежных выплат либо права на участие в призовом розыгрыше (лотерее) в соответствии с условиями конкретного опроса.
2.2. Участие в опросах через Панель является добровольным правом, а не обязанностью Пользователя. Пользователь самостоятельно решает, в каких опросах и когда участвовать, и вправе в любой момент отказаться от участия в опросах или от использования Сервиса в целом. Компания не гарантирует постоянное наличие доступных опросов для Пользователя; количество и тематика опросов определяются запросами заказчиков исследований и анкетными данными самого Пользователя.
2.3. Услуги Компании оказываются Пользователю бесплатно. Компания не взимает плату за регистрацию на Панели или участие в опросах. Все вознаграждения, полагающиеся Пользователю за прохождение опросов, выплачиваются непосредственно Компанияй (либо её партнером) на условиях, предусмотренных настоящей офертой и дополнительными условиями конкретного опроса или акции.
2.4. Компания обеспечивает защиту персональных данных Пользователей и использует предоставленные Пользователем данные исключительно для целей организации и проведения опросов, выплаты вознаграждений и улучшения работы Сервиса. Компания действует в соответствии с законодательством Республики Узбекистан о персональных данных, в том числе Законом «О персональных данных», и имеет соответствующую лицензию/свидетельство на обработку персональных данных (№ AA0000983, выданное уполномоченным органом при Кабинете Министров РУз). База персональных данных Пользователей зарегистрирована в Государственном реестре баз персональных данных, как того требует законодательство. Компания обязуется соблюдать требования законодательства Республики Узбекистан при обработке персональных данных Пользователей и обеспечивать их конфиденциальность. Подробная информация о целях, объеме и условиях обработки персональных данных приведена в Политике конфиденциальности (если применяется) либо предоставляется Пользователю при регистрации.
3. Регистрация на Сервисе и аккаунт Пользователя
3.1. Требования к Пользователю. Регистрацию на Панели вправе осуществлять дееспособные физические лица, достигшие 18-летнего возраста (совершеннолетия) либо иного возраста, с которого лицо приобрело дееспособность в полном объеме согласно законодательству Республики Узбекистан. Регистрируясь на Сервисе, Пользователь подтверждает, что соответствует указанным требованиям, а также что ранее не был удален или заблокирован Компанией за нарушения условий настоящей оферты.
3.2. Порядок регистрации. Для доступа к участию в опросах Пользователь должен пройти процедуру регистрации на сайте Панели, заполнив регистрационную форму и указав необходимую достоверную информацию о себе (включая, как минимум, имя, действующий адрес электронной почты, номер телефона и другие сведения по усмотрению Компании). Пользователь обязуется предоставлять при регистрации только правдивую, точную и полную информацию о себе. Компания имеет право запросить у Пользователя подтверждение предоставленных данных (например, посредством верификации email/телефона или предоставления копий документов) в случаях, когда это необходимо для исполнения обязательств (например, при выплате вознаграждения крупного размера или выдаче приза).
3.3. Единоразовая регистрация. Пользователь вправе иметь только одну учетную запись (аккаунт) на Панели. Множественная регистрация нескольких аккаунтов одним и тем же лицом строго запрещена. В случае выявления того, что один Пользователь имеет более одного аккаунта, Компания вправе по своему усмотрению заблокировать или удалить дублирующие аккаунты, а также аннулировать результаты опросов и/или вознаграждения, полученные по таким дополнительным аккаунтам.
3.4. Учетная запись. После успешной регистрации для Пользователя создается персональная учетная запись. Доступ к аккаунту осуществляется посредством указанных при регистрации уникальных учетных данных (логина и пароля). Пользователь несет ответственность за сохранность своих учетных данных и не должен передавать или раскрывать их третьим лицам. Все действия, совершенные в Сервисе с использованием логина и пароля Пользователя, считаются совершенными самим Пользователем. В случае утраты пароля или подозрения на несанкционированный доступ к аккаунту Пользователь обязуется незамедлительно уведомить об этом службу поддержки Компании для принятия мер.
4. Права и обязанности Пользователя
4.1. Права Пользователя:- Свободно и безвозмездно использовать возможности Сервиса для участия в доступных ему опросах, соблюдая условия настоящей оферты и требования действующего законодательства.- Получать своевременное вознаграждение за полностью и корректно пройденные опросы, в соответствии с условиями раздела 5 настоящей оферты.- Отказываться от участия в любых опросах по своему усмотрению, а также прекратить использование Сервиса в любое время.- Обращаться в службу поддержки Компании по любым вопросам, связанным с использованием Сервиса, получением вознаграждения, участием в розыгрышах и т.д. Контактная информация службы поддержки: info@prosurvey.uz (email) или @prosurveysupport в Telegram.- Требовать от Компании исполнения обязательств по настоящей оферте, включая выплату причитающихся денежных средств и предоставление информации об итогах розыгрышей призов.
4.2. Обязанности Пользователя:- Соблюдать условия настоящей оферты и выполнять правила пользования Сервисом надлежащим образом.- При регистрации указывать и в дальнейшем поддерживать актуальной только достоверную информацию о себе. В случае изменения персональных данных (например, фамилии, реквизитов банковской карты для выплат и т.п.) Пользователь должен своевременно обновить информацию в своем аккаунте либо уведомить Компанию.- Иметь не более одного зарегистрированного аккаунта и не создавать повторных учетных записей.- Лично использовать свой аккаунт для участия в опросах; не передавать доступ к своей учетной записи другим лицам и не пытаться использовать учетные записи других пользователей.- Добросовестно и внимательно отвечать на вопросы анкет во время прохождения опросов, давая осмысленные и правдивые ответы на поставленные вопросы. Запрещаются намеренно бессодержательные ответы, случайный набор символов, неотносящиеся к вопросу комментарии, заведомо ложные ответы и прочие недобросовестные действия при заполнении опросов. Компания оставляет за собой право на основании автоматизированных алгоритмов или проверки модератором признать ответы Пользователя несодержательными или недостоверными и аннулировать результаты такого опроса. В случае систематического или грубого нарушения данного требования Компания вправе заблокировать учетную запись Пользователя и отказать ему в дальнейших услугах Сервиса.- Не использовать Сервис в противоправных целях и не совершать действий, способных нарушить нормальную работу Панели. В частности, Пользователю запрещается: распространять через Сервис вредоносные программы или спам, публиковать оскорбительные или запрещенные материалы при общении (если такое предусмотрено), пытаться взломать функциональность сайта, либо иным образом нарушать законодательство РУз при использовании Панели.- Соблюдать конфиденциальность и не раскрывать третьим лицам какую-либо служебную или конфиденциальную информацию, ставшую известной Пользователю в процессе участия в опросах (например, содержание новых маркетинговых концепций или рекламы, которые тестируются в опросах) без письменного разрешения Компании.- Самостоятельно нести ответственность за все действия, совершенные на Сервисе под учетной записью Пользователя, а также за соблюдение требований законодательства при использовании полученных вознаграждений (например, уплата налогов, если это требуется законом).
5. Вознаграждение Пользователя и порядок выплат
5.1. Начисление вознаграждения за опросы. За участие Пользователя в опросах через Панель ему может предоставляться вознаграждение двух видов, в зависимости от условий конкретного опроса или программы лояльности: (a) прямая денежная выплата (фиксированная сумма денег за прохождение опроса), либо (b) право на участие в призовом розыгрыше, проводимом Компанией среди участников опроса. Условия о типе и размере вознаграждения сообщаются Пользователю до начала каждого опроса (например, в приглашении на опрос или в описании анкеты). Пользователь имеет право решать, принимать ли участие в опросе с предлагаемым видом вознаграждения.
5.2. Порядок выплаты денежных вознаграждений. Денежные вознаграждения за пройденные опросы начисляются на внутренний баланс аккаунта Пользователя в Панели (либо иным указанным способом). После накопления на балансе минимальной суммы, определенной правилами Панели (либо сразу после начисления, если технически возможно), Пользователь может запросить выплату денежных средств. Выплата осуществляется переводом на личную банковскую карту Пользователя. Для получения выплаты Пользователь должен указать в своем профиле действующий номер банковской карты, зарегистрированной на его имя, либо предоставить реквизиты иным предусмотренным способом. Компания осуществляет перевод средств на указанную Пользователем карту без взимания комиссии со стороны Сервиса (возможные комиссии банка-эмитента карты или платежной системы могут удерживаться независимо от Компании). При переводе не требуется от Пользователя вводить PIN-код или другой секретный код – достаточно корректно указать реквизиты карты, и выплата будет произведена автоматически. Компания прилагает усилия для своевременной выплаты средств, обычно в течение 1-3 рабочих дней с момента запроса вывода, однако в отдельных случаях возможны задержки по техническим или банковским причинам.
5.3. Призовые розыгрыши (лотереи). Если вознаграждением за участие в определенном опросе является участие в розыгрыше приза, условия такого розыгрыша (призовой фонд, количество победителей, критерии определения победителей, дата проведения розыгрыша и пр.) доводятся до сведения Пользователей отдельно – через описание опроса, правила акции или иным образом. Все розыгрыши проводятся Компанией честно и прозрачно, случайным образом определяя победителей среди Пользователей, выполнивших условия соответствующего опроса или акции. Участие в розыгрыше является для Пользователя бесплатным – никакой дополнительной платы, помимо факта участия в опросе, не требуется. Итоги розыгрышей подводятся в объявленные сроки, а результаты (список победителей или иная итоговая информация) публикуются на сайте Панели в разделе «Итоги» или аналогичном, доступном всем Пользователям, чтобы обеспечить прозрачность проведения акций. Каждый Пользователь, выигравший приз, будет уведомлен Компанией посредством электронной почты, телефона и/или через уведомление в аккаунте, с инструкциями о порядке получения приза. Невостребованные призы или призы, которые не удалось вручить победителю по независимым от Компании причинам (например, из-за неверно указанных контактных данных), могут быть распределены по усмотрению Компании повторно или аннулированы, согласно условиям конкретной акции.
5.4. Налогообложение. Денежные вознаграждения, выплачиваемые Пользователю, являются доходом Пользователя. Компания осуществляет необходимые действия налогового агента, если это прямо возложено на нее законодательством (например, удерживает налог на доходы физических лиц при выплате вознаграждений, если того требуют нормы Налогового кодекса). В противном случае Пользователь самостоятельно несет ответственность за декларирование и уплату налогов со полученных доходов, когда это требуется по закону. В отношении призов, полученных в результате розыгрышей, Компания действует в соответствии с законодательством о стимулирующих лотереях и акциях; в случае необходимости Компания может запросить у победителя дополнительные данные для налоговой отчетности (например, ИНН, паспортные данные) либо вручить приз через специализированного налогового агента (банк или иную организацию).
6. Права и обязанности Компании
6.1. Права Компании:- Запрашивать у Пользователя дополнительную информацию или документы, необходимые для выполнения условий оферты (например, подтверждение личности при подозрении на мошенничество, подтверждение права получения вознаграждения и пр.). В случае непредоставления Пользователем запрошенных данных Компания вправе приостановить обслуживание данного Пользователя до выполнения запроса.- Приостанавливать либо прекращать доступ Пользователя к Сервису (в том числе блокировать учетную запись) в случае нарушения Пользователем условий настоящей оферты, законодательства или прав третьих лиц. Блокировка аккаунта может быть временной (на период расследования обстоятельств нарушения) или постоянной – в зависимости от характера нарушения. О факте блокировки и ее причинах Компания по возможности уведомляет Пользователя, используя контактные данные аккаунта.- В одностороннем порядке вносить изменения в функционал Сервиса, интерфейс Панели, программу вознаграждений, правила проведения опросов и иные аспекты предоставления услуг, улучшая или изменяя сервис. Такие изменения (не затрагивающие непосредственно текст настоящей оферты) могут вводиться без предварительного уведомления Пользователя, путем публикации новой информации на сайте либо внутри интерфейса Панели. Если изменения требуют согласия Пользователя (например, новые условия акций), такое согласие будет запрошено отдельным подтверждением.- Удалять или изменять любую информацию, размещенную Пользователем на Сервисе, если она противоречит условиям настоящей оферты либо требованиям закона, либо по соответствующему требованию уполномоченных органов.- Осуществлять профилактические работы, временно приостанавливая работу Сервиса, по возможности в нерабочие часы и с предварительным уведомлением Пользователей на сайте или иным способом.- Привлекать третьих лиц (партнеров, подрядчиков) для исполнения своих обязательств по настоящему договору, оставаясь ответственной перед Пользователем за действия таких лиц как за свои собственные.
6.2. Обязанности Компании:- Обеспечивать возможность Пользователю пользоваться Сервисом в соответствии с условиями оферты, при корректном использовании Пользователем учетных данных и соблюдении им установленных правил. Компания гарантирует предоставление Пользователю доступа к Панели 24 часа в сутки 7 дней в неделю, за исключением периодов проведения технического обслуживания или устранения неполадок, о которых Пользователи по возможности уведомляются заранее.- Предоставлять Пользователю достоверную информацию о правилах участия в опросах, порядке и размерах вознаграждения, условиях розыгрышей и других существенных условиях предоставляемых услуг. Вся актуальная информация размещается на сайте Панели и/или доводится до сведения Пользователя посредством сообщений (email-рассылки, уведомления в аккаунте и пр.).- Начислять и выплачивать Пользователю вознаграждения, заработанные в результате прохождения опросов, в порядке и сроки, предусмотренные настоящей офертой. Компания несет ответственность за учет баланса Пользователя и корректность произведенных расчетов вознаграждения. В случае обнаружения ошибки в расчетах (со стороны как Компании, так и Пользователя) стороны стремятся урегулировать ситуацию путем взаимных сверок данных и при необходимости осуществления доплаты либо возврата излишне выплаченных сумм.- Обеспечивать соблюдение требований законодательства Республики Узбекистан при обработке персональных данных Пользователя, включая защиту конфиденциальности таких данных. Компания принимает необходимые организационно-технические меры для защиты персональной информации Пользователей от несанкционированного доступа, утраты или раскрытия. Персональные данные Пользователя могут быть использованы только в пределах, определенных настоящей офертой и действующим законодательством, и не передаются третьим лицам без согласия Пользователя, за исключением случаев, прямо предусмотренных законом (например, по требованию суда или правоохранительных органов).- Сохранять прозрачность и честность проведения призовых розыгрышей. Компания обязуется публиковать итоги розыгрышей призов на своем Сервисе (раздел «Итоги» или аналогичный) после их проведения, обеспечивая возможность для каждого участника убедиться в справедливости результатов. По запросу Пользователя Компания может предоставить информацию о порядке проведения конкретного розыгрыша (например, о методе случайного определения победителя) в пределах разумного, не раскрывая при этом коммерческой тайны или уязвимости, которые могли бы привести к злоупотреблениям.- Рассматривать обращения и жалобы Пользователей, связанные с использованием Сервиса или выполнением условий оферты. Компания обязуется ответить на обращение Пользователя в срок не позднее 10 рабочих дней с даты его получения, если иной срок не предусмотрен законодательством или особыми условиями.
7. Ответственность сторон
7.1. Ответственность Пользователя: В случае нарушения Пользователем своих обязанностей по настоящей оферте (включая предоставление недостоверных данных, множественную регистрацию, недобросовестное прохождение опросов, нарушение прав третьих лиц или иные нарушения) Пользователь может быть привлечен к ответственности в соответствии с законодательством Республики Узбекистан. Компания вправе применять к нарушителю меры, указанные в разделе 6.1 (блокировка аккаунта, отказ в обслуживании и т.п.), а также требовать возмещения убытков, если они возникли по вине Пользователя. Пользователь самостоятельно несет ответственность за любой ущерб, причиненный им третьим лицам при использовании Сервиса, а также за соблюдение требований закона при распоряжении полученными от Компании денежными средствами или призами.
7.2. Ответственность Компании: Компания несет ответственность перед Пользователем исключительно в пределах, предусмотренных законодательством и настоящей офертой. Компания не является должником Пользователя в части предоставления каких-либо гарантий помимо прямо указанных: в частности, Компания не гарантирует достижение Пользователем какого-либо конкретного дохода от участия в опросах, определенного количества приглашений на опросы, коммерческой пригодности Сервиса для целей Пользователя и т.п. Компания не несет ответственности за неполучение Пользователем вознаграждения по причинам, не зависящим от Компании – например, если Пользователь сам нарушил условия опроса, предоставил некорректные реквизиты для выплаты, либо если банк-эмитент карты отклонил транзакцию. Также Компания не отвечает за сбои в работе Сервиса, вызванные воздействием непреодолимой силы (форс-мажора) либо техническими причинами вне зоны контроля Компании (например, сбои в сети Интернет, в оборудовании дата-центра, действия третьих лиц). В этих случаях обязательства Компании могут быть временно приостановлены на время действия препятствия, и это не считается нарушением договора.
7.3. Ограничение ответственности: В максимально допустимой законом степени ответственность Компании перед Пользователем ограничивается суммой фактически начисленного, но не выплаченного вознаграждения данному Пользователю либо стоимостью причитающегося ему приза. Компания ни при каких обстоятельствах не несет ответственности за какие-либо косвенные или непредвиденные убытки Пользователя, включая упущенную выгоду, потерю данных, моральный вред и т.п., возникшие в связи с использованием либо невозможностью использования Сервиса. Данное ограничение не применяется в случаях, когда ответственность не может быть ограничена или исключена в силу прямого указания закона.
7.4. Стороны освобождаются от ответственности за полное или частичное неисполнение своих обязательств по настоящему договору, если докажут, что надлежащее исполнение оказалось невозможным вследствие обстоятельств непреодолимой силы (форс-мажора), возникших после заключения договора. К таким обстоятельствам относятся чрезвычайные и непредотвратимые при данных условиях события, включая стихийные бедствия, военные действия, массовые беспорядки, акты государственных органов и пр.. Сторона, для которой создалась невозможность исполнения обязательств, должна как можно скорее уведомить другую Сторону о наступлении форс-мажора. В период действия обстоятельств непреодолимой силы обязательства сторон приостанавливаются. Если форс-мажор длится более трех месяцев подряд, любая Сторона вправе расторгнуть договор в одностороннем порядке путем уведомления другой Стороны.
8. Разрешение споров и применимое право
8.1. Все споры и разногласия, которые могут возникнуть между Сторонами в связи с исполнением настоящей оферты, решаются путем переговоров и обмена претензиями. Сторона, считающая свои права нарушенными, должна направить письменную претензию другой Стороне с указанием сути требования и обоснования. Стороны обязуются рассмотреть полученную претензию в разумный срок (не более 10 рабочих дней) и принять меры к урегулированию спора.
8.2. В случае если Стороны не смогут достичь согласия путем переговоров, спор подлежит разрешению в судебном порядке в соответствии с действующим законодательством Республики Узбекистан. Компетенция суда определяется в соответствии с процессуальным законодательством РУз – иск может быть предъявлен, в частности, по месту регистрации Компании, если иное не предусмотрено законом. До обращения в суд соблюдение досудебного (претензионного) порядка урегулирования спора является обязательным, за исключением случаев, когда для конкретного вида спора законодательством установлено иное.
8.3. Применимым правом по всем вопросам, не урегулированным настоящей офертой, является материальное право Республики Узбекистан. Положения оферты толкуются в соответствии с законодательством РУз. Во всем, что прямо не предусмотрено в тексте оферты, Стороны будут руководствоваться нормами действующих законов и иных нормативных правовых актов Республики Узбекистан.
8.4. Настоящая публичная оферта составлена на русском языке. В случае необходимости ее перевода на другой язык (например, для использования на другом языковом разделе сайта), русскоязычная версия будет иметь приоритет в случае расхождений. Договор публичной оферты считается заключенным и исполняемым на территории Республики Узбекистан.
9. Заключительные положения
9.1. Настоящая оферта вступает в силу с момента ее акцепта Пользователем (см. п.1.2) и действует бессрочно до момента отзыва оферты Компанией либо до прекращения договора по иным основаниям. Компания вправе отозвать (аннулировать) настоящую публичную оферту в любое время путем удаления ее текста с сайта Панели, при этом обязательства, принятые Компанией в отношении ранее акцептовавших оферту Пользователей, сохраняют силу на условиях, действовавших на момент акцепта.
9.2. Если какое-либо условие настоящей оферты будет признано недействительным или незаконным по решению суда, это не влечет недействительности остальных условий. В таком случае Стороны остаются связанными обязательствами по всем остальным положениям оферты, которые не затронуты недействительностью, и предпримут необходимые действия для замены недействительного условия действительным, максимально приближенным по смыслу.
9.3. Бездействие со стороны Компании в случае нарушения Пользователем положений настоящей оферты не означает отказа Компании от права предпринимать соответствующие действия позднее. Отказ от какого-либо права или условия в одном случае не означает отказа в любом другом случае.
9.4. Все уведомления, сообщения и запросы в рамках настоящей оферты должны направляться Сторонами друг другу в письменной форме. Допускается использование электронной почты и иных средств электронной коммуникации, при условии что можно достоверно установить отправителя. Официальные контактные данные Компании для связи указаны в разделе 4.1 (права Пользователя) и на веб-сайте Панели. Пользователь при регистрации указывает свои актуальные контактные данные и обязуется поддерживать их в актуальном состоянии.
9.5. Настоящая публичная оферта является полноценным договором между Пользователем и Компанией. Пользователь подтверждает, что внимательно ознакомился со всеми условиями данной оферты до начала использования Сервиса, все условия ему понятны, и он принимает их добровольно, в своем интересе, без принуждения.
10. Реквизиты и контактные данные Компании

Правообладатель Сервиса / Исполнитель услуг:
Общество с ограниченной ответственностью «PROSURVEY»

ИНН: 312401712

Лицензия на обработку персональных данных:
№ AA0000983 (Государственный центр персонализации при Кабинете Министров РУз)

E-mail: info@prosurvey.uz
Telegram (поддержка): @prosurveysupport`,
    },
    uz: {
      title: "Ommaviy oferta",
      back: "Orqaga",
      fullText: `
Ommaviy oferta onlayn so‘rovnoma panelidan foydalanish bo‘yicha «ProSurvey»

1. Umumiy qoidalar
1.1. Ushbu hujjat «PROSURVEY» MChJ (keyingi o‘rinlarda – Kompaniya) tomonidan taqdim etilgan ommaviy oferta hisoblanadi va noma’lum shaxslar doirasiga – «ProSurvey» onlayn so‘rovnoma paneli (keyingi o‘rinlarda – Panel yoki Servis) tashrif buyuruvchilari va foydalanuvchilariga qaratilgan. Ushbu hujjat shartnomaning barcha muhim shartlarini o‘z ichiga oladi va O‘zbekiston Respublikasi Fuqarolik Kodeksining 367 va 369-moddalariga muvofiq ommaviy oferta hisoblanadi.
1.2. Ushbu ofertani qabul qilish (aksept) foydalanuvchining Kompaniya bilan ushbu shartlarda shartnoma tuzishga rozilik bildiruvchi harakatlarini amalga oshirishi hisoblanadi. Xususan, foydalanuvchining Panel saytida ro‘yxatdan o‘tishi va Servisdan foydalanishni boshlashi to‘liq va so‘zsiz aksept hisoblanadi. Oferta aksept qilingani paytdan boshlab Kompaniya va Foydalanuvchi o‘rtasida shartnoma tuzilgan hisoblanadi.
1.3. Agar foydalanuvchi ushbu ofertaning biror shartiga rozi bo‘lmasa, u holda ro‘yxatdan o‘tmasligi va Servisdan foydalanmasligi kerak. Paneldan foydalanishni davom ettirish foydalanuvchining ushbu ommaviy oferta shartlariga to‘liq roziligini anglatadi. Ofertani qabul qilgan shaxs shu bilan birga O‘zbekiston Respublikasi qonunchiligiga muvofiq shartnoma tuzish uchun zarur huquqiy layoqat va muomala layoqatiga ega ekanini tasdiqlaydi.
1.4. Kompaniya ushbu ommaviy oferta shartlariga o‘zgartirishlar kiritish huquqini o‘zida saqlab qoladi. O‘zgarishlar Panel saytida yangilangan matn joylashtirilgandan keyin kuchga kiradi yoki e’lon qilinganidan boshlab boshqa ko‘rsatilgan muddat o‘tganidan keyin. Kompaniya foydalanuvchilarni bunday o‘zgarishlar haqida ularning kuchga kirishidan kamida 10 (o‘n) ish kuni oldin sayt orqali xabardor qilish majburiyatini oladi. O‘zgarishlardan keyin Servisdan foydalanishni davom ettirish foydalanuvchining yangilangan oferta shartlariga roziligini anglatadi. O‘zgarishlar orqaga qaytarilmaydi va o‘z kuchga kirishidan oldin vujudga kelgan huquq va majburiyatlarga taalluqli bo‘lmaydi.
2. Shartnoma predmeti (Kompaniya xizmatlari)
2.1. Ushbu shartnoma bo‘yicha Kompaniya foydalanuvchiga «ProSurvey» onlayn-platformasidan foydalanish imkoniyatini beradi. Bu orqali foydalanuvchi uchinchi shaxslar – Kompaniya mijozlari yoki hamkorlari buyurtmasiga ko‘ra o‘tkaziladigan so‘rovlarda (sotsiologik, marketing va boshqa tadqiqotlarda) qatnashishi mumkin. Foydalanuvchi esa, o‘z navbatida, Panel orqali so‘rovlarda ishtirok etib, buning uchun pul mukofoti yoki lotereyada (sovrinli o‘yinlarda) ishtirok etish huquqini oladi. Bu shartlar har bir alohida so‘rov uchun alohida belgilanadi.
2.2. Panel orqali so‘rovlarda qatnashish foydalanuvchining huquqi, majburiyati emas. Foydalanuvchi qaysi so‘rovlarda va qachon ishtirok etishini mustaqil ravishda belgilaydi hamda istalgan vaqtda so‘rovda qatnashishdan yoki Servisdan foydalanishni to‘xtatishdan voz kechishi mumkin. Kompaniya foydalanuvchiga doimiy ravishda so‘rovlar mavjudligini kafolatlamaydi. So‘rovlarning soni va mavzusi buyurtmachilar talabiga hamda foydalanuvchining shaxsiy anketadagi ma’lumotlariga qarab belgilanadi.
2.3. Kompaniya xizmatlari foydalanuvchi uchun bepul ko‘rsatiladi. Kompaniya ro‘yxatdan o‘tish yoki so‘rovlarda ishtirok etish uchun hech qanday to‘lov olmaydi. Foydalanuvchiga so‘rovlar uchun tegishli mukofotlar ushbu oferta va har bir alohida so‘rov/aksiyaga oid qo‘shimcha shartlar asosida Kompaniya (yoki uning hamkori) tomonidan to‘lab beriladi.
2.4. Kompaniya foydalanuvchilarning shaxsiy ma’lumotlarini himoya qiladi va ularni faqat so‘rovlarni tashkil etish va o‘tkazish, mukofotlarni to‘lash va Servisni yaxshilash maqsadida ishlatadi. Kompaniya O‘zbekiston Respublikasining «Shaxsiy ma’lumotlar to‘g‘risida»gi qonuni talablari asosida faoliyat yuritadi hamda tegishli litsenziya/shtat guvohnomasiga ega (№ AA0000983, Vazirlar Mahkamasi huzuridagi vakolatli organ tomonidan berilgan). Foydalanuvchilarning shaxsiy ma’lumotlar bazasi Davlat shaxsiy ma’lumotlar bazalari reyestrida ro‘yxatga olingan. Kompaniya foydalanuvchi ma’lumotlarini qayta ishlashda qonun talablariga amal qiladi va ularning maxfiyligini ta’minlaydi. Ma’lumotlarning qayta ishlanishi bo‘yicha batafsil ma’lumot maxfiylik siyosatida (agar mavjud bo‘lsa) yoki foydalanuvchiga ro‘yxatdan o‘tishda taqdim etiladi.
3. Servisda ro‘yxatdan o‘tish va foydalanuvchi akkaunti
3.1. Foydalanuvchiga qo‘yiladigan talablar. Panelda ro‘yxatdan o‘tish huquqiga faqat huquqiy layoqatli jismoniy shaxslar ega. Ular 18 yoshga (balog‘atga) yetgan bo‘lishi yoki O‘zbekiston Respublikasi qonunchiligiga muvofiq to‘liq muomala layoqatiga ega bo‘lishlari kerak. Ro‘yxatdan o‘tish orqali foydalanuvchi ushbu talabga mos kelishini va ilgari Kompaniya tomonidan shartnoma shartlarini buzganlik uchun uning akkaunti o‘chirilmagan yoki bloklanmaganini tasdiqlaydi.
3.2. Ro‘yxatdan o‘tish tartibi. So‘rovlarda ishtirok etish uchun foydalanuvchi Panel saytida ro‘yxatdan o‘tishi va ro‘yxatdan o‘tish formasini to‘ldirishi kerak. Bunda ishonchli ma’lumotlarni kiritishi lozim (kamida ism, amaldagi elektron pochta manzili, telefon raqami va Kompaniya talab qilishi mumkin bo‘lgan boshqa ma’lumotlar). Foydalanuvchi faqat haqiqiy, to‘liq va aniq ma’lumotlarni taqdim etishga majbur. Kompaniya zarurat tug‘ilganda foydalanuvchidan kiritilgan ma’lumotlarni tasdiqlashni talab qilish huquqiga ega (masalan, email/telefonni tasdiqlash yoki hujjat nusxasini so‘rash). Bu ayniqsa katta miqdordagi mukofot to‘lanishi yoki yutuq berilishi oldidan qo‘llanilishi mumkin.
3.3. Bir martalik ro‘yxatdan o‘tish. Foydalanuvchi Panelda faqat bitta akkauntga ega bo‘lishi mumkin. Bir shaxs tomonidan bir nechta akkaunt ochish qat’iyan taqiqlanadi. Agar foydalanuvchida bir nechta akkaunt aniqlansa, Kompaniya dublikat akkauntlarni bloklash yoki o‘chirish hamda ular orqali olingan mukofotlarni bekor qilish huquqiga ega.
3.4. Akkaunt. Ro‘yxatdan muvaffaqiyatli o‘tilgandan so‘ng foydalanuvchi uchun shaxsiy akkaunt yaratiladi. Akkauntga kirish faqat ro‘yxatdan o‘tishda ko‘rsatilgan login va parol orqali amalga oshiriladi. Foydalanuvchi o‘z login va parolini maxfiy saqlashga majbur va ularni uchinchi shaxslarga oshkor qilmasligi kerak. Foydalanuvchi akkauntidan foydalangan holda amalga oshirilgan barcha harakatlar bevosita foydalanuvchining o‘zi tomonidan qilingan hisoblanadi. Agar foydalanuvchi parolini yo‘qotsa yoki akkauntiga ruxsatsiz kirilganiga shubha qilsa, u holda bu haqda darhol Kompaniya qo‘llab-quvvatlash xizmatiga xabar berishi shart.
4. Foydalanuvchining huquq va majburiyatlari
4.1. Foydalanuvchining huquqlari:
Ushbu ofertada va amaldagi qonunchilikda belgilangan tartibda Servis imkoniyatlaridan bepul va erkin foydalanib, mavjud so‘rovlarda qatnashish.
To‘liq va to‘g‘ri o‘tkazilgan so‘rovlari uchun o‘z vaqtida mukofot olish, ushbu ofertaning 5-bo‘limida ko‘rsatilgan shartlarga muvofiq.
Istalgan so‘rovda qatnashishdan voz kechish, shuningdek, istalgan vaqtda Servisdan foydalanishni to‘xtatish.
Servisdan foydalanish, mukofotlarni olish, lotereyalarda qatnashish bo‘yicha barcha savollar yuzasidan Kompaniya qo‘llab-quvvatlash xizmatiga murojaat qilish. Qo‘llab-quvvatlash aloqa ma’lumotlari: info@prosurvey.uz (email) yoki @prosurveysupport (Telegram).
Ushbu oferta bo‘yicha Kompaniya majburiyatlarini bajarilishini, jumladan, pul mablag‘larini to‘lashni va sovrinli o‘yinlar natijalari to‘g‘risidagi ma’lumotlarni taqdim etishni talab qilish.
4.2. Foydalanuvchining majburiyatlari:
Ushbu ofertada belgilangan shartlarga rioya qilish va Servisdan to‘g‘ri foydalanish.
Ro‘yxatdan o‘tishda va keyinchalik faqat haqiqiy, aniq va yangilangan ma’lumotlarni kiritish. Shaxsiy ma’lumotlari (masalan, familiya, bank karta rekvizitlari va h.k.) o‘zgarganda, akkauntini yangilash yoki Kompaniyaga xabar berish.
Panelda faqat bitta akkauntga ega bo‘lish va boshqa akkauntlar yaratmaslik.
Akkauntini faqat o‘zi uchun ishlatish, uni uchinchi shaxslarga bermaslik va boshqa foydalanuvchilar akkauntidan foydalanishga urinish qilmaslik.
So‘rovlarda savollarga vijdonan va diqqat bilan javob berish, ma’nosiz, yolg‘on yoki tasodifiy belgilar kiritmaslik. Kompaniya foydalanuvchining javoblarini avtomatlashtirilgan algoritmlar yoki moderator orqali tekshirishi va sifatsiz deb topsa, natijalarni bekor qilish huquqiga ega. Agar foydalanuvchi ushbu talabni muntazam ravishda buzsa, Kompaniya uning akkauntini bloklash huquqiga ega.
Servisdan noqonuniy maqsadlarda foydalanmaslik va Panel ishiga zarar yetkazadigan harakatlarni amalga oshirmaslik (viruslar tarqatish, spam yuborish, haqoratomuz material joylash, saytni buzishga urinish va h.k.).
So‘rovlarda qatnashish jarayonida o‘ziga ma’lum bo‘lgan xizmat yoki maxfiy ma’lumotlarni (masalan, yangi reklama konsepsiyalari) uchinchi shaxslarga oshkor qilmaslik.
Akkauntidan foydalangan holda bajarilgan barcha harakatlar uchun shaxsan javob berish hamda olgan mukofotlari bo‘yicha qonun talab qilgan hollarda soliqlarni to‘lash.
5. Foydalanuvchini mukofotlash va to‘lov tartibi
5.1. So‘rovlar uchun mukofot berish. Panel orqali so‘rovlarda ishtirok etgan foydalanuvchi quyidagi ikki turdagi mukofotdan birini olishi mumkin:(a) to‘g‘ridan-to‘g‘ri pul mukofoti (so‘rovni o‘tkazib bo‘lgach belgilangan miqdordagi pul);(b) Kompaniya tomonidan o‘tkaziladigan sovrinli o‘yinda (lotereyada) ishtirok etish huquqi.Har bir so‘rov yoki dastur shartlarida mukofot turi va miqdori oldindan foydalanuvchiga ma’lum qilinadi (masalan, so‘rovga taklifda yoki anketada). Foydalanuvchi taklif qilingan shartlarga qarab so‘rovda ishtirok etish yoki qilmaslikni mustaqil hal qiladi.
5.2. Pul mukofotlarini to‘lash tartibi. So‘rov uchun hisoblangan pul mukofotlari foydalanuvchining Paneldagi shaxsiy balansiga (yoki boshqa ko‘rsatilgan usul orqali) tushiriladi. Balansda minimal miqdor yig‘ilgandan so‘ng (yoki texnik imkoniyat bo‘lsa darhol) foydalanuvchi mablag‘ni yechib olishni so‘rashi mumkin. To‘lov foydalanuvchining shaxsiy bank kartasiga o‘tkaziladi. Foydalanuvchi to‘lov olish uchun akkauntida o‘z nomiga ochilgan bank karta raqamini ko‘rsatishi kerak. Kompaniya mablag‘larni foydalanuvchi ko‘rsatgan karta hisobiga hech qanday qo‘shimcha komissiyasiz o‘tkazadi (biroq bank yoki to‘lov tizimi komissiya ushlab qolishi mumkin). To‘lov amalga oshirilishi uchun foydalanuvchidan PIN-kod yoki boshqa maxfiy raqam kiritish talab qilinmaydi – faqat karta rekvizitlarini to‘g‘ri ko‘rsatishi kifoya. Mablag‘lar odatda 1–3 ish kuni ichida to‘lanadi, ammo texnik yoki bankdagi muammolar tufayli kechikish bo‘lishi mumkin.
5.3. Sovrinli o‘yinlar (lotereyalar). Agar so‘rov sharti bo‘yicha mukofot sifatida sovrinli o‘yinda qatnashish nazarda tutilgan bo‘lsa, uning shartlari (sovrin jamg‘armasi, g‘oliblar soni, aniqlash mezonlari, o‘tkazilish sanasi va h.k.) foydalanuvchiga alohida ma’lum qilinadi – so‘rov tavsifida yoki aksiyaning qoidalarida. Barcha lotereyalar Kompaniya tomonidan halol va shaffof tarzda o‘tkaziladi, g‘oliblar esa tasodifiy tanlov asosida aniqlanadi. Foydalanuvchi uchun ishtirok bepul, ya’ni qo‘shimcha to‘lov talab qilinmaydi. Natijalar belgilangan muddatlarda e’lon qilinadi va Panel saytida «Natijalar» bo‘limida hamma uchun ochiq tarzda joylanadi. G‘olib bo‘lgan foydalanuvchi Kompaniya tomonidan elektron pochta, telefon yoki akkauntdagi xabarnoma orqali xabardor qilinadi va mukofotni olish tartibi bo‘yicha ko‘rsatmalar oladi. Agar mukofot foydalanuvchining xatosi (masalan, noto‘g‘ri aloqa ma’lumotlari) tufayli berilmasa, u holda Kompaniya mukofotni qayta taqsimlash yoki bekor qilish huquqiga ega.
5.4. Soliqqa tortish. Foydalanuvchiga to‘lanadigan pul mukofotlari uning daromadi hisoblanadi. Qonunchilik talab qilsa, Kompaniya soliq agenti sifatida zarur soliqlarni ushlab qoladi (masalan, jismoniy shaxs daromad solig‘i). Aks holda, foydalanuvchi olgan daromadini mustaqil ravishda deklaratsiya qilib, soliq to‘lashi shart. Lotereya orqali olingan sovrinlar ham amaldagi qonunchilikka muvofiq soliqqa tortilishi mumkin. Zarurat bo‘lsa, Kompaniya g‘olibdan qo‘shimcha ma’lumot (masalan, INN, pasport ma’lumotlari) so‘rashi yoki mukofotni soliq agenti orqali berishi mumkin.
6. Kompaniyaning huquq va majburiyatlari
6.1. Kompaniyaning huquqlari:
Ushbu oferta shartlarini bajarish uchun foydalanuvchidan qo‘shimcha ma’lumot yoki hujjatlar talab qilish (masalan, firibgarlikdan shubhalanganda yoki mukofotni olish huquqini tasdiqlash zarur bo‘lganda). Agar foydalanuvchi talab qilingan ma’lumotni taqdim etmasa, Kompaniya xizmat ko‘rsatishni vaqtincha to‘xtatib turish huquqiga ega.
Foydalanuvchi ushbu oferta, qonunchilik yoki uchinchi shaxslarning huquqlarini buzgan taqdirda Servisga kirishni vaqtincha yoki butunlay to‘xtatish (akkauntni bloklash). Bloklash vaqtinchalik (tekshiruv davrida) yoki doimiy bo‘lishi mumkin. Imkon bo‘lsa, Kompaniya foydalanuvchini bloklash va uning sabablarini akkauntdagi aloqa ma’lumotlari orqali xabardor qiladi.
Servis funksionalligi, interfeysi, mukofotlash dasturi, so‘rov o‘tkazish tartibi va boshqa xizmat ko‘rsatish jihatlariga o‘zgartirish kiritish. Agar bu o‘zgarishlar foydalanuvchidan qo‘shimcha rozilik talab qilsa (masalan, yangi aksiya shartlari), bunday rozilik alohida so‘raladi.
Foydalanuvchi tomonidan Servisga joylashtirilgan, ushbu oferta yoki qonunga zid bo‘lgan har qanday ma’lumotni o‘chirish yoki o‘zgartirish, shuningdek vakolatli davlat organlari talabi asosida choralar ko‘rish.
Texnik xizmat ko‘rsatish ishlarini olib borish uchun Servis ishini vaqtincha to‘xtatib turish, iloji boricha ish vaqtidan tashqari va foydalanuvchilarni oldindan xabardor qilgan holda.
O‘z majburiyatlarini bajarishda uchinchi shaxslarni (hamkorlar, pudratchilar) jalb qilish, biroq ular harakatlari uchun foydalanuvchi oldida o‘zi javobgar bo‘lish.
6.2. Kompaniyaning majburiyatlari:
Foydalanuvchi login va parolni to‘g‘ri ishlatgan hamda qoidalarga rioya qilgan taqdirda, Servisdan foydalanish imkoniyatini ta’minlash. Kompaniya Servisdan 24/7 foydalanish imkonini kafolatlaydi (texnik xizmat yoki nosozliklar bundan mustasno).
Foydalanuvchiga so‘rovlarda ishtirok etish qoidalari, mukofotlash tartibi va miqdori, lotereya shartlari va boshqa muhim ma’lumotlarni to‘g‘ri taqdim etish. Barcha yangilangan ma’lumotlar Panel saytida yoki akkaunt ichidagi xabarnomalar, email orqali yetkaziladi.
Foydalanuvchining balansini yuritish, mukofotlarni hisoblash va belgilangan muddatlarda to‘lab berish. Agar hisob-kitobda xatolik yuz bersa, tomonlar ma’lumotlarni tekshiradi va kerak bo‘lsa, to‘lovni qayta amalga oshiradi.
Foydalanuvchilarning shaxsiy ma’lumotlarini O‘zbekiston Respublikasi qonunchiligiga muvofiq qayta ishlash, ularning maxfiyligini ta’minlash va uchinchi shaxslarga roziliksiz bermaslik (qonunda belgilangan hollardan tashqari, masalan sud yoki huquqni muhofaza qiluvchi organlar talabi bo‘lsa).
Sovrinli o‘yinlarni halol va shaffof o‘tkazish, natijalarni Panel saytida («Natijalar» bo‘limida) e’lon qilish va foydalanuvchilarga o‘z qatnashgan o‘yin natijalarini tekshirish imkoniyatini berish. Zarur hollarda, foydalanuvchiga o‘yinning o‘tkazilish tartibi haqida asosiy ma’lumotlarni taqdim etish (lekin tijorat sirini oshkor qilmaslik sharti bilan).
Foydalanuvchilarning murojaat va shikoyatlarini ko‘rib chiqish va ularga 10 ish kunidan kechiktirmay javob berish (agar qonunchilik yoki alohida shartlar boshqa muddatni belgilamagan bo‘lsa).
7. Tomonlarning javobgarligi
7.1. Foydalanuvchining javobgarligi.Agar foydalanuvchi ushbu oferta shartlarini buzsa (shu jumladan, noto‘g‘ri ma’lumot berish, bir nechta akkaunt ochish, so‘rovlarda sifatsiz yoki yolg‘on javob berish, uchinchi shaxslarning huquqlarini buzish va boshqa qoidabuzarliklar), u O‘zbekiston Respublikasi qonunchiligiga muvofiq javobgar bo‘ladi. Kompaniya foydalanuvchining akkauntini bloklash, xizmat ko‘rsatishni rad etish yoki boshqa choralarni qo‘llash huquqiga ega, shuningdek foydalanuvchi aybi bilan yetkazilgan zararni undirishni talab qilishi mumkin. Foydalanuvchi Servisdan foydalanish jarayonida uchinchi shaxslarga yetkazilgan zarar uchun ham o‘zi javob beradi. Bundan tashqari, foydalanuvchi olgan mukofotlari bo‘yicha qonunda belgilangan hollarda soliqlarni mustaqil ravishda to‘lashi shart.
7.2. Kompaniyaning javobgarligi.Kompaniya foydalanuvchi oldida faqat qonunchilik va ushbu ofertada belgilangan doirada javobgar bo‘ladi. Kompaniya foydalanuvchiga ma’lum bir daromad kafolatlamaydi, doimiy so‘rovlar taklif qilinishini ta’minlamaydi va Servisni foydalanuvchining shaxsiy maqsadlari uchun to‘liq mos kelishini va’da qilmaydi. Agar foydalanuvchi shartlarni buzgan, noto‘g‘ri karta raqamini ko‘rsatgan yoki bank to‘lovni rad etgan bo‘lsa, Kompaniya mukofot to‘lanmaganligi uchun javobgar emas. Shuningdek, Kompaniya internetdagi nosozliklar, ma’lumot markazidagi texnik muammolar yoki uchinchi shaxslar harakatlari sababli Servis ishlashidagi uzilishlar uchun ham javobgar emas. Bunday hollarda majburiyatlar vaqtincha to‘xtatilishi mumkin va bu shartnoma buzilishi hisoblanmaydi.
7.3. Javobgarlikni cheklash.Qonun ruxsat bergan eng yuqori darajada Kompaniyaning foydalanuvchi oldidagi javobgarligi faqat foydalanuvchiga hisoblangan, ammo hali to‘lanmagan mukofot summasi yoki unga tegishli sovrin qiymati bilan cheklanadi. Kompaniya hech qachon foydalanuvchining bilvosita yo‘qotishlari (masalan, boy berilgan foyda, ma’lumotlarning yo‘qolishi, ma’naviy zarar va h.k.) uchun javobgar bo‘lmaydi. Bu cheklov qonun to‘g‘ridan-to‘g‘ri taqiqlamagan hollarda amal qiladi.
7.4. Fors-major holatlar.Agar tomonlar o‘z majburiyatlarini bajarolmasalar, bunga fors-major sabab bo‘lganini isbotlashlari shart. Fors-major – bu favqulodda va oldini olib bo‘lmaydigan vaziyatlar (tabiiy ofatlar, urush, tartibsizliklar, davlat organlarining qarorlari va h.k.). Bunday holat yuzaga kelganda, tomonlar imkon qadar tezroq bir-birini xabardor qilishi kerak. Fors-major davrida majburiyatlar to‘xtatiladi. Agar fors-major uzluksiz uch oydan ortiq davom etsa, tomonlardan har biri shartnomani bir tomonlama bekor qilish huquqiga ega.
8. Nizolarni hal qilish va qo‘llaniladigan huquq
8.1. Tomonlar o‘rtasida ushbu ofertani bajarish bilan bog‘liq kelib chiqadigan barcha nizolar va kelishmovchiliklar muzokaralar va da’vo-arizalar almashuvi orqali hal qilinadi. O‘zini huquqi buzilgan deb hisoblagan tomon ikkinchi tomonga yozma da’vo yuborishi va unda talabning mohiyati hamda asoslarini ko‘rsatishi shart. Da’vo olingach, tomonlar uni oqilona muddat ichida (10 ish kunidan oshmagan holda) ko‘rib chiqib, nizoni hal qilishga intilishlari kerak.
8.2. Agar tomonlar muzokaralar orqali kelishuvga erisha olmasalar, nizo O‘zbekiston Respublikasi qonunchiligiga muvofiq sud tartibida hal etiladi. Sud vakolatlari amaldagi protsessual qonunchilikka muvofiq belgilanadi. Xususan, da’vo Kompaniya ro‘yxatdan o‘tgan joydagi sudga taqdim etilishi mumkin, agar qonunda boshqacha tartib nazarda tutilmagan bo‘lsa. Sudga murojaat qilishdan oldin majburiy da’vo tartibiga rioya qilish shart (ayrim hollarda qonunda boshqacha tartib ko‘zda tutilgan bo‘lishi mumkin).
8.3. Ushbu oferta bilan tartibga solinmagan barcha masalalarda O‘zbekiston Respublikasining moddiy huquqi qo‘llaniladi. Oferta qoidalari O‘zbekiston Respublikasi qonunlariga muvofiq talqin qilinadi. Oferta matnida to‘g‘ridan-to‘g‘ri ko‘rsatilmagan holatlarda tomonlar amaldagi qonun hujjatlariga amal qilishlari shart.
8.4. Ushbu ommaviy oferta rus tilida tuzilgan. Agar zarurat tug‘ilib boshqa tilga tarjima qilinsa (masalan, saytning boshqa til bo‘limida foydalanish uchun), tafovut yuzaga kelganida rus tilidagi versiya ustuvor hisoblanadi. Oferta bo‘yicha shartnoma O‘zbekiston Respublikasi hududida tuzilgan va bajarilgan hisoblanadi.
9. Yakuniy qoidalar
9.1. Ushbu oferta foydalanuvchi tomonidan aksept qilingan paytdan (1.2-bandga qarang) kuchga kiradi va Kompaniya tomonidan bekor qilinmaguncha yoki shartnoma boshqa asoslarda tugamaguncha muddatsiz amal qiladi. Kompaniya istalgan vaqtda ushbu ommaviy ofertani bekor qilish huquqiga ega. Bunda matn Panel saytida olib tashlanadi. Shunga qaramay, Kompaniya oldinroq ofertani qabul qilgan foydalanuvchilarga nisbatan majburiyatlarini, o‘sha paytdagi shartlarga muvofiq, bajarishda davom etadi.
9.2. Agar ushbu ofertaning biror bandi sud qaroriga ko‘ra haqiqiy emas yoki noqonuniy deb topilsa, bu boshqa shartlarning haqiqiy emasligini anglatmaydi. Tomonlar qolgan bandlarga amal qilishda davom etadilar va iloji boricha o‘sha bandni ma’nosi jihatdan yaqin, amaldagi qonunga muvofiq band bilan almashtirish choralarini ko‘radilar.
9.3. Foydalanuvchi tomonidan ushbu oferta shartlari buzilganida Kompaniya chora ko‘rmagan bo‘lsa, bu uning keyinchalik o‘z huquqlaridan voz kechganini anglatmaydi. Bir marta berilgan imtiyoz boshqa holatlarda ham avtomatik tarzda qo‘llanilmaydi.
9.4. Ushbu oferta doirasidagi barcha xabarlar, bildirishnomalar va so‘rovlar yozma shaklda yuborilishi kerak. Elektron pochta va boshqa elektron aloqa vositalaridan foydalanishga ruxsat beriladi, agar jo‘natuvchini aniq aniqlash imkoni bo‘lsa. Kompaniyaning rasmiy aloqa ma’lumotlari 4.1-bandda (foydalanuvchining huquqlari) va Panel saytida ko‘rsatilgan. Foydalanuvchi ro‘yxatdan o‘tayotganda o‘zining amaldagi aloqa ma’lumotlarini taqdim etishi va ularni yangilab turishi shart.
9.5. Ushbu ommaviy oferta foydalanuvchi bilan Kompaniya o‘rtasidagi to‘liq shartnoma hisoblanadi. Foydalanuvchi Servisdan foydalanishni boshlashdan oldin ushbu shartlarning barchasini diqqat bilan o‘qib chiqqanini, ularni to‘liq tushunganini va ularni hech qanday majburlashsiz, o‘z xohishi bilan qabul qilganini tasdiqlaydi.
10. Kompaniyaning rekvizitlari va aloqa ma'lumotlari

Servis egasi / Xizmat ko'rsatuvchi:
MChJ «PROSURVEY»

INN: 312401712

Shaxsiy ma'lumotlarni qayta ishlash litsenziyasi:
№ AA0000983 (O'zbekiston Respublikasi Vazirlar Mahkamasi huzuridagi Davlat personallashtirish markazi tomonidan berilgan)

E-mail: info@prosurvey.uz
Telegram (qo'llab-quvvatlash): @prosurveysupport`,
    },
  };

  const t = translations[language || "ru"];

  // Функция для обработки ссылок в тексте
  const processTextWithLinks = (text) => {
    const lines = text.split('\n');
    return lines.map((line, index) => {
      // Обработка email ссылок
      if (line.includes('info@prosurvey.uz')) {
        const parts = line.split('info@prosurvey.uz');
        return (
          <div key={index}>
            {parts[0]}
            <a 
              href="mailto:info@prosurvey.uz" 
              className="text-[#5E5AF6] underline hover:text-[#4A47D1] transition-colors"
            >
              info@prosurvey.uz
            </a>
            {parts[1]}
          </div>
        );
      }
      
      // Обработка Telegram ссылок
      if (line.includes('@prosurveysupport')) {
        const parts = line.split('@prosurveysupport');
        return (
          <div key={index}>
            {parts[0]}
            <a 
              href="https://t.me/prosurveysupport" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-[#5E5AF6] underline hover:text-[#4A47D1] transition-colors"
            >
              @prosurveysupport
            </a>
            {parts[1]}
          </div>
        );
      }
      
      return <div key={index}>{line}</div>;
    });
  };

  return (
    <div className="min-h-screen bg-[#F4F4FF]">
      <div className="fixed top-0 left-0 right-0 z-30">
        <Header />
      </div>

      <div className="fixed top-40 bottom-32 left-0 right-0 z-10">
        <div className="h-full px-6 py-4 overflow-y-auto custom-scrollbar">
          <h2 className="text-2xl font-bold text-[#5E5AF6] text-center mb-8">
            {t.title}
          </h2>

          <div className="text-base leading-relaxed text-gray-800">
            {processTextWithLinks(t.fullText)}
          </div>
        </div>
      </div>

      <div className="fixed bottom-3 left-0 right-0 z-20 p-4 pb-[env(safe-area-inset-bottom)]">
        <div className="max-w-md mx-auto">
          <div className="rounded-2xl bg-[#EDEAFF] p-2">
            <button
              onClick={() => navigate("/main?tab=profile")}
              className="w-full h-[48px] rounded-xl bg-gradient-to-r from-[#5538F9] to-[#7C65FF] text-white font-semibold active:scale-[0.99] transition"
            >
              {t.back}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PublicOfferScreen;